trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- template: build.yaml

- template: deploy.yaml
  parameters:
    environmentName: dev

- template: deploy.yaml
  parameters:
    environmentName: qa

