parameters:
- name: environmentName
  type: string

stages:
- stage: Deploy_${{ parameters.environmentName }}
  variables:
    ${{ if eq(parameters.environmentName, 'dev') }}:
        artifactPath: $[ stageDependencies.Build.BuildJob.outputs['setPath.artifactPath'] ]
    ${{ if eq(parameters.environmentName, 'qa') }}:
        artifactPath: $[ stageDependencies.Deploy_dev.ForwardVariable.outputs['forwardSetPath.artifactPath'] ]
  jobs:
  - deployment: DeployTo${{ parameters.environmentName }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to ${{ parameters.environmentName }}"
              echo "Artifact path: $(artifactPath)"
  - job: ForwardVariable
    steps:
    - script: |
         echo "##vso[task.setvariable variable=artifactPath;isOutput=true]/drop/$(Build.BuildId)"
      name: forwardSetPath


