parameters:
- name: environmentName
  type: string

stages:
- stage: Deploy_${{ parameters.environmentName }}
  variables:
    artifactPath: $[ stageDependencies.Build.BuildJob.outputs['setPath.artifactPath'] ]
  jobs:
  - deployment: DeployTo${{ parameters.environmentName }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to ${{ parameters.environmentName }}"
              echo "Artifact path: $(artifactPath)"

